app.config(function($httpProvider,$stateProvider,$urlRouterProvider){ 

    $httpProvider.defaults.transformRequest = function(obj) {
        // console.log(obj)
        var arr = []
        for(var i in obj) {
            arr.push(i + "=" +obj[i])
        }
        // console.log(arr.join("&"))
        return arr.join("&") // id=1&fromid=2
}
$httpProvider.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

    $urlRouterProvider.otherwise('/admin')
    // $urlRouterProvider.when('','/admin')
    $stateProvider
    .state({
        name:'admin',
        url:'/admin',
        views:{
            "header":{
                templateUrl:"../views/admin/public/header.html"
            },
            "sidebar":{
                templateUrl:"../views/admin/public/sidebar.html"
            },
            "content":{
                templateUrl:"../views/admin/admin-index.html",
                controller:"adminCtrl"
            },
            "footer":{
                templateUrl:"../views/admin/public/footer.html"
            },
        }
    })
    .state({
        name:'admin.food',
        url:'/food',
        views:{
            'content@':{
                templateUrl:'../views/admin/food.html',
                controller:'foodCtrl'
            }
        }
    })
    .state({
        name:'admin.food.add',
        url:'/add',
        views:{
            'content@':{
                templateUrl:'../views/admin/food_add_edit.html',
                controller:'foodAddCtrl'
            }
        }
    })
    .state({
        name:'admin.food.edit',
        url:'/edit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/food_add_edit.html',
                controller:'foodAddCtrl'
            }
        }
    })
    .state({
        name:'admin.foodCate',
        url:'/foodCate',
        views:{
            'content@':{
                templateUrl:'../views/admin/foodCate.html',
                controller:'foodCateCtrl'
            }
        }
    })
    .state({
        name:'admin.foodCate.add',
        url:'/foodCateadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/foodCate_add_edit.html',
                controller:'foodCateAddCtrl'
            }
        }
    })
    .state({
        name:'admin.foodCate.edit',
        url:'/foodCateedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/foodCate_add_edit.html',
                controller:'foodCateAddCtrl'
            }
        }
    })
    .state({
        name:'admin.region',
        url:'/region',
        views:{
            'content@':{
                templateUrl:'../views/admin/region.html',
                controller:'regionCtrl'
            }
        }
    })
    .state({
        name:'admin.region.add',
        url:'/regionadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/region_add_edit.html',
                controller:'regionAddCtrl'
            }
        }
    })
    .state({
        name:'admin.region.edit',
        url:'/regionedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/region_add_edit.html',
                controller:'regionAddCtrl'
            }
        }
    })
    .state({
        name:'admin.friendLink',
        url:'/friendLink',
        views:{
            'content@':{
                templateUrl:'../views/admin/friendLink.html',
                controller:'friendLinkCtrl'
            }
        }
    })
    .state({
        name:'admin.friendLink.add',
        url:'/friendLinkadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/friendLink_add_edit.html',
                controller:'friendLinkAddCtrl'
            }
        }
    })
    .state({
        name:'admin.friendLink.edit',
        url:'/friendLinkedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/friendLink_add_edit.html',
                controller:'friendLinkAddCtrl'
            }
        }
    })
    .state({
        name:'admin.banner',
        url:'/banner',
        views:{
            'content@':{
                templateUrl:'../views/admin/banner.html',
                controller:'bannerCtrl'
            }
        }
    })
    .state({
        name:'admin.banner.add',
        url:'/banneradd',
        views:{
            'content@':{
                templateUrl:'../views/admin/banner_add_edit.html',
                controller:'bannerAddCtrl'
            }
        }
    })
    .state({
        name:'admin.banner.edit',
        url:'/banneredit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/banner_add_edit.html',
                controller:'bannerAddCtrl'
            }
        }
    })
    .state({
        name:'admin.singlePage',
        url:'/singlePage',
        views:{
            'content@':{
                templateUrl:'../views/admin/singlePage.html',
                controller:'singlePageCtrl'
            }
        }
    })
    .state({
        name:'admin.singlePage.add',
        url:'/singlePageadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/singlePage_add_edit.html',
                controller:'singlePageAddCtrl'
            }
        }
    })
    .state({
        name:'admin.singlePage.edit',
        url:'/singlePageedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/singlePage_add_edit.html',
                controller:'singlePageAddCtrl'
            }
        }
    })
    .state({
        name:'admin.nav',
        url:'/nav',
        views:{
            'content@':{
                templateUrl:'../views/admin/nav.html',
                controller:'navCtrl'
            }
        }
    })
    .state({
        name:'admin.nav.add',
        url:'/navadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/nav_add_edit.html',
                controller:'navAddCtrl'
            }
        }
    })
    .state({
        name:'admin.nav.edit',
        url:'/navedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/nav_add_edit.html',
                controller:'navAddCtrl'
            }
        }
    })
    .state({
        name:'admin.company',
        url:'/company',
        views:{
            'content@':{
                templateUrl:'../views/admin/company.html',
                controller:'companyCtrl'
            }
        }
    })
    .state({
        name:'admin.company.add',
        url:'/companyadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/company_add_edit.html',
                controller:'companyAddCtrl'
            }
        }
    })
    .state({
        name:'admin.company.edit',
        url:'/companyedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/company_add_edit.html',
                controller:'companyAddCtrl'
            }
        }
    })
    .state({
        name:'admin.news',
        url:'/news',
        views:{
            'content@':{
                templateUrl:'../views/admin/news.html',
                controller:'newsCtrl'
            }
        }
    })
    .state({
        name:'admin.news.add',
        url:'/newsadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/news_add_edit.html',
                controller:'newsAddCtrl'
            }
        }
    })
    .state({
        name:'admin.news.edit',
        url:'/newsedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/news_add_edit.html',
                controller:'newsAddCtrl'
            }
        }
    })
    .state({
        name:'admin.setting',
        url:'/setting',
        views:{
            'content@':{
                templateUrl:'../views/admin/setting.html',
                controller:'settingCtrl'
            }
        }
    })
    .state({
        name:'admin.setting.add',
        url:'/settingadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/setting_add_edit.html',
                controller:'settingAddCtrl'
            }
        }
    })
    .state({
        name:'admin.setting.edit',
        url:'/settingedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/setting_add_edit.html',
                controller:'settingAddCtrl'
            }
        }
    })
    .state({
        name:'admin.shop',
        url:'/shop',
        views:{
            'content@':{
                templateUrl:'../views/admin/shop.html',
                controller:'shopCtrl'
            }
        }
    })
    .state({
        name:'admin.shop.add',
        url:'/shopadd',
        views:{
            'content@':{
                templateUrl:'../views/admin/shop_add_edit.html',
                controller:'shopAddCtrl'
            }
        }
    })
    .state({
        name:'admin.shop.edit',
        url:'/shopedit/:id',
        views:{
            'content@':{
                templateUrl:'../views/admin/shop_add_edit.html',
                controller:'shopAddCtrl'
            }
        }
    })
}).run()